### ISSUE TITLE
Zowe SDKs - API usage examples

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-client-python-sdk#10]
Similar to zowe/zowe-cli#751 - each package should contain overview info and documentation on how to leverage its APIs in a README. In this case we can leverage some of the content currently in the main README.

**Comment by zFernand0** [comment]
Some usage example have been created in the top level readme file.
We can consider adding a Readme.md under each package (similar to the NodeJS SDK)
https://github.com/zowe/zowe-cli/blob/master/packages/zosfiles/README.md

Closing in favor of:
- #147
