### ISSUE TITLE
Update documentation for running tests

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#105]
Should probably suggest `pytest` instead of `green` which has caused issues
`pytest tests/unit`
`pytest tests/integration`

Should also have instructions for creating zowe.config.json to run integration tests instead of old v1 profiles.

https://github.com/zowe/zowe-client-python-sdk/blob/next/CONTRIBUTING.md#running-tests

**Comment by antondelchev** [comment]
I'd like to work on this one.
