### ISSUE TITLE
Investigate linter and code formatter

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#111]
Currently `flake8` is run in the build workflow, but the CONTRIBUTING.md file doesn't recommend any linters or code formatters to use.

We should pick a state of the art linter and recommend for all contributors to use it. Same for a code formatter like `black` if we decide there is value in having one.

**Comment by deadaf** [comment]
Hi @t1m0thyj ,I would like to contribute to this issue. Could you please clarify whether you would like me to add a section about using `flake8` specifically in the `CONTRIBUTING.md` file, or if you would like me to research and recommend other linters as well? Thank you!

**Comment by t1m0thyj** [comment]
@deadaf Thanks for your interest in this issue 🙂 I think it would be good to update `CONTRIBUTING.md` to (1) mention this project uses `flake8` and (2) suggest using `black` as a formatter. If you create a pull request, please open it against the `next` branch 🙂

**Comment by deadaf** [comment]
Hi @t1m0thyj 
I have made some changes in PR #156  to address the issue.

On a related note, I came across this repository while searching for a LFX mentorship program, and I'm delighted to inform you that I have applied for the same.I'm eager to contribute to the project in any way I can. If there's anything else I can help with, please let me know. I'm more than happy to contribute further.

Thank you!
