### ISSUE TITLE
Load secure values from multiple credential entries on Windows

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#134]
On Windows the maximum credential length is 2560 bytes. If the JSON object in `Zowe/secure_config_props` exceeds this length, Zowe CLI works around the limitation by splitting the credential string across multiple entries. The final one is terminated by a NUL byte (`\0`). For example:
**Zowe/secure_config_props-1**
```
{"C:/Users/User/.zowe/zowe.con
```
**Zowe/secure_config_props-2**
```
fig.json":{...}}␀
```

**Comment by zFernand0** [comment]
Documentation:
- Look for `CredentialBlobSize` in https://learn.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credentiala

Node.js SDK implementation:
https://github.com/zowe/imperative/blob/9269753532a0201284aa07417a9d2be9e1598ded/packages/security/src/DefaultCredentialManager.ts#L293-L310
