### ISSUE TITLE
Load profile properties from environment variables

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#136]
When loading a profile from team config, have an opt-in flag to support loading of properties from environment variables.

For example, in an environment where I don't want to store credentials securely, the user and password properties should be loaded from `ZOWE_OPT_USER` and `ZOWE_OPT_PASSWORD` respectively.

**Comment by bhavukkalra** [comment]
Hey there @t1m0thyj. Just for clarification purposes for this issue. Is the idea here to load the Environment variables from a user provided, local `.env` file?

**Comment by t1m0thyj** [comment]
Environment variables take priority over values defined in the config
Can load list of properties (host, port, user, password, etc) from schema

**Comment by t1m0thyj** [comment]
Environment variables have `ZOWE_OPT_` prefix
`camelCase` properties in config/schema JSON map to `snake_case` in environment variables
For example: Env Var to override `rejectUnauthorized` property is `ZOWE_OPT_REJECT_UNAUTHORIZED`
