### ISSUE TITLE
Install next using pip problem

### ISSUE THREAD

**Issue by skorzhevsky** [zowe/zowe-client-python-sdk#137]
Hi,
  I'm trying to install @next branch according to the readme:

```
"Note: You can also install prerelease versions of the Zowe SDK from GitHub with the following command where <tagName>is the latest GitHub release tag:

pip install -f https://github.com/zowe/zowe-client-python-sdk/releases/tag/<tagName> zowe>=1.0.0.dev0"

```
but this fails:

```
(venv) PS C:\MyData\git\Temp> pip install -f https://github.com/zowe/zowe-client-python-sdk/releases/tag/v1.0.0.dev7 zowe>=1.0.0.dev7

Looking in links: https://github.com/zowe/zowe-client-python-sdk/releases/tag/v1.0.0.dev7
ERROR: Could not find a version that satisfies the requirement zowe>=1.0.0.dev7 (from versions: 0.0.1, 0.2.0)
ERROR: No matching distribution found for zowe>=1.0.0.dev7

```

**Comment by t1m0thyj** [comment]
Thanks for reporting this, seems like running `pip install` from a GitHub release no longer works for some reason.

Could you please try these updated install instructions to install `v1.0.0.dev8`?
> Download the ZIP file from the [latest release](https://github.com/zowe/zowe-client-python-sdk/releases/latest), extract it, and run the following command:
> 
> ```
> pip install --no-index --no-deps <path where zip is extracted>/*.whl
> ```

**Comment by skorzhevsky** [comment]
Hi, i installed downloaded libraries with pip and w/o additional flags, but specified all whl explicitly:

`pip install zowe_core_for_zowe_sdk-1.0.0.dev7-py3-none-any.whl ...`

Wildcard doesn't work in my case (Windows 10):

```
C:\git\pr1\blibs>pip install *.whl
WARNING: Requirement '*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.
```

**Comment by t1m0thyj** [comment]
@skorzhevsky We recently published pre-release wheels to PyPI. You should be able to install with `pip install -U --pre zowe`
