### ISSUE TITLE
Requests rejected because received from a remote site

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#14]
When making a z/OSMF request with the SDK, I get the following error:
> IZUG846W: An HTTP request for a z/OSMF REST service was received from a remote site. The request was rejected, however, because the remote site "" is not permitted to z/OSMF server "IZUSVR" on target system "xyz.net:1443"

Some sites require that the header "X-CSRF-ZOSMF-HEADER" be supplied on z/OSMF REST requests. The Node.js SDK always includes this header, and adding it below with an empty value (`"X-CSRF-ZOSMF-HEADER": ""`) seems to fix the issue:
https://github.com/zowe/zowe-client-python-sdk/blob/24d1b36798f7cfae79a432835e9a0304a2a8e15e/src/core/zowe/core_for_zowe_sdk/sdk_api.py#L38-L40

Perhaps this is a regression of #1.

**Comment by gcartier94** [comment]
Thank you @t1m0thyj!

I'll work on this =)

**Comment by Sudhanshu-Dubey14** [comment]
Hey,
I was getting the same issue when trying to do `submit_from_mainframe(jcl_path)` which I resolved using @t1m0thyj 's suggestion.
But now when I do `submit_from_local_file(jcl_path)`, I get the same error.

How can I solve this?
Thanks.

**Comment by gcartier94** [comment]
Issue fixed on the latest release.

Thank you @sosadchuk for your contribution!
