### ISSUE TITLE
Add steps on how to setup the project locally

### ISSUE THREAD

**Issue by bhavukkalra** [zowe/zowe-client-python-sdk#152]
In the current state of the `readme.md` file the steps for local setup are not clearly defined.

What it currently shows is how to use the project after downloading the binaries from PIP.
That is helpful from the perspective of the users, but not for developers that might be coming in the future 
contributing to the open source project

Proposal - The steps should go something like this 

1. `git clone [REPO_URL]`

2. Make a virtual environment. `conda`, `venv` etc.

3. `cd src/core/zowe`

4. `python setup.py` (For installing the core package)

and so on

**Comment by Aman123lug** [comment]
@bhavukkalra I want to work on this

**Comment by Aman123lug** [comment]
@t1m0thyj @bhavukkalra anyone working on this?

**Comment by t1m0thyj** [comment]
Yes, this is being worked on in https://github.com/zowe/zowe-client-python-sdk/pull/204 🙂
