### ISSUE TITLE
Not able to setup the project locally on windows 10

### ISSUE THREAD

**Issue by bhavukkalra** [zowe/zowe-client-python-sdk#153]
I was trying to setup the project locally on a windows 10 machine. These are the steps that I took so far

1) Edit the [build.sh](https://github.com/zowe/zowe-client-python-sdk/blob/master/build.sh) file and replace `python3` with python and ran it in git bash. `Result` - The file executed successfully with no errors

2) Make a `test.py` file and write this code 

`from zowe.zos_console_for_zowe_sdk import Console`

I am getting this error - 

"from zowe.zos_console_for_zowe_sdk import Console
ModuleNotFoundError: No module named 'zowe'"

Note - I am running the file from the same environment as of running the `bash` file

Was there something wrong with my installation? Did I miss any steps?

cc - @t1m0thyj

**Comment by t1m0thyj** [comment]
@bhavukkalra Thanks for your interest in the Python SDK 🙂 Here are the steps I would suggest to setup the project locally:
1. Clone the `next` branch of the project. This branch is where the latest developments have been made.
2. (optional) Create a virtual env for your Python development environment: `python -m venv venv`
3. Install dependencies for the project: `pip install -r requirements.txt`
  This step will also symlink local packages which should fix the error "No module named 'zowe'".

Running the `build.sh` script is not required to set up the project locally. It is used to package the SDKs into wheels.

**Comment by bhavukkalra** [comment]
Hey thanks for an impromptu reply. Here are the steps I did now

1. Done
2. Created the virtual environment and activated it
3. Ran `pip install -r requirements.txt` [Got an Error at this step]

DEPRECATION: lark-parser is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lark-parser ... done


  DEPRECATION: lxml is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

Error - `Running setup.py install for lxml ... error
  error: subprocess-exited-with-error`

`C:\Users\bhavu\AppData\Local\Temp\pip-install-mzjistyq\lxml_ad148854ecbc4e84838cd9279fb4d78c\src\lxml\includes/etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
      Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2`


  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.



(I am going to search up on this issue)

**Comment by t1m0thyj** [comment]
@bhavukkalra What version of Python are you running? Since the `lxml` package contains native binaries, you may need to adjust its version in "requirements.txt" to match your Python version.

**Comment by bhavukkalra** [comment]
I am currently on `python 3.11`.

I did a little bit of digging by myself and got to know that `python 3.11` is the issue here. 
See below link for ref - 

https://bugs.launchpad.net/lxml/+bug/1969912
https://github.com/janeczku/calibre-web/issues/2606

It was suggested by most of the folks that python 3.11 is unstable with the `lxml`. Hence downgraded to python 3.10.

Result - `pip install -r requirements.txt` Now ran Successfully.

Also changed the `requirements.txt` lxml version to `4.9.1`

**Comment by t1m0thyj** [comment]
@bhavukkalra Please feel free to open a pull request against the `next` branch for these changes - (1) to document the command for installing dependencies and (2) to recommend using Python 3.10 or older 🙂

**Comment by bhavukkalra** [comment]
Thanks for giving the "go ahead" at it Timothy. On it! Opening another Issue to track the progress of the Docs and closing this one!
