### ISSUE TITLE
Document the project setup steps

### ISSUE THREAD

**Issue by bhavukkalra** [zowe/zowe-client-python-sdk#154]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

When a new contributor visits the project for contribution. It could be quiet overwhelming to see the whole project structure and different files that are contained in it!
Currently there are step by step docs available on how to setup the project locally.

**Describe your enhancement idea**

- Add the step by step commands required to setup the project
- Add a starter script "template" to confirm if the project was set up correctly
- Document the pitfalls that were faced in the issue #153 for python3.11

**Describe alternatives you've considered**

As this is a growing project, I am hoping the starter docs would change over time. Giving the new contributors something to get started with the setup and start contributing

**Provide any additional context**

I was thinking, I'll first start with the `readme.md` file and then gradually add this to our official docs at `/docs`. But that is open to discussion.

cc- @adam-wolfe @t1m0thyj

**Comment by achiverram28** [comment]
Yeah , I can support for the macOS setup, because even I faced some issues in setting up . I can document the steps and help other macOs users to follow the steps , if they face any error

**Comment by bhavukkalra** [comment]
That would be great actually. Could you point out specifically where you encountered the error with a UNIX like environment? 
I can go ahead and add those changes as well in the draft PR #155.

For me it was specifically the python3.11 version mismatch with the `lxml` package (`but that was not a windows based error`)

Did you encountered any errors specific to MACOS?

**Comment by achiverram28** [comment]
In macOs , also , there was an issue because of lxml I was using python3 . For mac users they can downgrade their python versions using pyenv locally for their project and then run the pip install - r requirements.txt . After this all the imports work propely
