### ISSUE TITLE
Upload coverage to Codecov issue

### ISSUE THREAD

**Issue by achiverram28** [zowe/zowe-client-python-sdk#158]
I just made a version number change in the requirements.txt to setup up proper environment in my macos , and comitted that code to my code branch . I am continuously getting this issue.
<img width="1082" alt="3A976241-B9DA-4B56-AF04-ADD0496E0702" src="https://github.com/zowe/zowe-client-python-sdk/assets/97288756/6c0c9890-5062-4508-84a4-88dccccbcdfc">

I check from both cli and ui , this issue persists .

Its says no token found in the verbose , after this the error comes 

This issue persists in the latest version of the codecov. 
Repository of codecov - https://github.com/codecov/codecov-action 
I guess we need to modify sdk-build.yaml

**Comment by traeok** [comment]
Hi @achiverram28 ,

Is this what happens after pushing a commit to a new fork of the Python SDK? Or are you trying to adapt the workflows on this repo to work on your fork?

I tested making a fork and pushing a test commit to it, but the workflows are not running. This should be the expected behavior since GitHub typically does not include the workflows when you fork a repository.

**Comment by achiverram28** [comment]
Pushing a commit to a new fork of the Python SDK. It shows this  and because of this I am not able to make a PR

**Comment by traeok** [comment]
Ah okay, I see. The first time that you click on the "Actions" tab, it will ask if you want to enable workflows for this repo:

![image](https://github.com/zowe/zowe-client-python-sdk/assets/86500639/7e4c2e40-4618-4793-8cd2-858102523f6a)

I think its worth documenting that our workflows will not work as expected when run on forks. For now, manually disabling actions should work - it should run the workflows in our repo once the PR is created.

Thanks for bringing this to our attention!

**Comment by achiverram28** [comment]
No worries . Should I close this issue , then ?
