### ISSUE TITLE
Specify the port in the Getting Started -> Basic Usage page in the documentation

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-client-python-sdk#162]
**Describe the bug**

In the SDK documentation, it does not show how a user should specify the port to connect to z/OSMF. (see https://zowe-client-python-sdk.readthedocs.io/en/latest/usage/examples.html and https://zowe-client-python-sdk.readthedocs.io/en/latest/classes/core/api_connection.html) 

**Expected and actual results**

It would be helpful if the documentation made it clear that the host_url specified in the connection object should include a port number if the intended port number differs from the default of 443.

**Comment by t1m0thyj** [comment]
We should update the example in the docs to demonstrate creating a profile object, since connection objects have been deprecated in the main branch. The updated example would look something like this:
```python
from zowe.zos_console_for_zowe_sdk import Console
profile = {
    "host": "<zosmfHost>",
    "port": 443,
    "user": "<user>",
    "password": "<password>",
}

my_console = Console(profile)
```

**Comment by Myrausman** [comment]
@t1m0thyj, Can you assign me this task

**Comment by t1m0thyj** [comment]
@Myrausman Sure 🙂 I've assigned you to the issue.

The link seems to have changed to: https://zowe-client-python-sdk.readthedocs.io/en/latest/classes/core/connection.html
