### ISSUE TITLE
Allow pip install of new versions/releases

### ISSUE THREAD

**Issue by aviVzm05** [zowe/zowe-client-python-sdk#177]
Hi,

Could you see if we can get the new releases available via pip install?

This would help immensely as there are cases where we can't download the source from github.

Thank you,
Avinash

**Comment by t1m0thyj** [comment]
Related to #80

**Comment by Drizer909** [comment]
hey this looks nice for enchancement , can you assign this issue to work on it

**Comment by t1m0thyj** [comment]
Added to v1 milestone - this is still relevant as we need to publish to pip for our next stable release.

**Comment by zFernand0** [comment]
I know they are in pre-release state right now but people should be able to install from PyPi.
- `pip install -U --pre zowe` 
- `pip install zowe==1.0.0.dev15`

https://pypi.org/project/zowe/#history

Closing! 😋
