### ISSUE TITLE
[zos-files] `download_dsn` fails to write contents to disk

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#179]
```
Traceback (most recent call last):
  File "C:\Users\user\Projects\zowe\zowe-client-python-sdk\test.py", line 14, in <module>
    files_api.download_dsn(dsname, "test-download.txt")
  File "c:\users\user\projects\zowe\zowe-client-python-sdk\src\zos_files\zowe\zos_files_for_zowe_sdk\files.py", line 405, in download_dsn
    shutil.copyfileobj(raw_response, f)
  File "C:\Python310\lib\shutil.py", line 198, in copyfileobj
    fdst_write(buf)
TypeError: write() argument must be str, not bytes
```

**Comment by Aman123lug** [comment]
I want to work on this issue. I want contribute a medium level problems can i work on this?

**Comment by t1m0thyj** [comment]
@Aman123lug Feel free to work on this issue, although you'll need a z/OSMF environment to be able to reproduce the issue and test a fix 🙂 

To gain access to a mainframe running z/OSMF, you could sign up for the [OMP Cobol Programming Course](https://openmainframeproject.org/projects/cobol-programming-course/) or request a 3-day trial from IBM [here](https://early-access.ibm.com/software/support/trial/cst/welcomepage.wss?siteId=1571&tabId=4294&w=1).

**Comment by t1m0thyj** [comment]
To work around this issue, the file can be downloaded to a string and then saved to a file:
```python
dsn_contents = files.get_dsn_content(dsname)
with open(dsname.split(".")[-1] + ".txt", 'w') as f:
    f.write(dsn_contents["response"])
```
