### ISSUE TITLE
[zos-jobs] Add method to change the job class

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#182]
Add a method to the Python zos-jobs SDK to call the z/OSMF REST API `PUT /zosmf/restjobs/jobs/<jobname>/<jobid>` with `class` parameter

* z/OSMF REST API documentation: https://www.ibm.com/docs/en/zos/2.5.0?topic=interface-change-job-class
* Python zos-jobs SDK in the "main" branch: https://github.com/zowe/zowe-client-python-sdk/tree/main/src/zos_jobs
* Node.js zos-jobs SDK for comparison: https://github.com/zowe/zowe-cli/blob/master/packages/zosjobs/src/ModifyJobs.ts

**Comment by aadityasinha-dotcom** [comment]
@t1m0thyj please assign it to me :)
