### ISSUE TITLE
Add Logger class to core SDK

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#185]
* [ ] Add a Logger class to the core SDK
  * It can likely be a wrapper around the built-in Python `logging` package: https://docs.python.org/3/library/logging.html
* [ ] Add logging messages throughout all the SDKs where it would be beneficial
  * [ ] SdkApi class should have DEBUG or TRACE level messages to aid in debugging REST errors
  * [ ] Replace `show_warnings` flag on ProfileManager class with the logger

**Comment by Aman123lug** [comment]
I want to work on this please assign me

**Comment by t1m0thyj** [comment]
@Aman123lug Thanks for your interest in the Zowe Python SDK!

There is some research needed for this enhancement before it's ready to be implemented, so I've tagged the issue with the "Research Needed" label.

In the meantime, feel free to work on any other issues - a good place to start is ones tagged as "good-first-issue" 🙂
