### ISSUE TITLE
Run SDK build workflow in multiple environments

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#194]
For the [`sdk-build.yaml` workflow](https://github.com/zowe/zowe-client-python-sdk/blob/main/.github/workflows/sdk-build.yml), we should add a matrix to run the build across multiple OSes and Python versions:
* Windows, Linux, macOS
* Python 3.7, 3.8, 3.9, 3.10, 3.11

**Comment by Aman123lug** [comment]
This issue is a good first issue I will start contributing from this.
Okay! I need a add build support for multiple OS with different python versions.

**Comment by t1m0thyj** [comment]
Thanks, I've assigned the issue to you 🙂 

Here's an example of a multi-dimensional matrix for GH workflows that may be helpful: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-multi-dimension-matrix

**Comment by Aman123lug** [comment]
can you please review my PR and if i did something let me know 
thanks for sharing the docs
