### ISSUE TITLE
[core] Dynamically generate invalid config files in unit tests

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#209]
> Instead of adding a new `zowe.config.json` and `zowe.schema.json` file to the repo for every combination of invalid config/schema that we want to test, could we generate the invalid JSON files programmatically?
> 
> For example, in the test that requires "invalid.zowe.config.json" we could do something like this:
> ```python
> with open(self.original_file_path, 'r') as f:
>     original_config = commentjson.load(f)
> original_config["$schema"] = "./invalid.zowe.schema.json"
> with open(os.path.join(self.custom_dir, "invalid.zowe.config.json"), 'w') as f:
>     commentjson.dump(original_config, f)
> ```

_Originally posted by @t1m0thyj in https://github.com/zowe/zowe-client-python-sdk/pull/192#discussion_r1301781987_

**Comment by aadityasinha-dotcom** [comment]
Please assign this to me :relaxed:
