### ISSUE TITLE
create_data_set + delete_data_set: datasets are not being created properly if there is a '#' symbol in their names

### ISSUE THREAD

**Issue by KUGDev** [zowe/zowe-client-python-sdk#211]
**Describe the bug**

I've encountered an issue creating and deleting dataset with a '#' symbol in it's name
Example: MYNAME.TEST#ZWE

**Expected and actual results**

1. Expected: dataset MYNAME.TEST#ZWE is created and deleted by these functions
2. Actual: dataset is created as MYNAME.TEST#ZWE. If I try to delete the MYNAME.TEST#ZWE dataset, created manually, it's giving an error, as it tries to find MYNAME.TEST

**Describe your environment**

z/OS 2.5, zowe-client-python-sdk 1.0.0-dev.10

**Additional context**

**Comment by adam-wolfe** [comment]
Implemented by PR: #212
