### ISSUE TITLE
Refactor function definitions to avoid dictionaries as parameters

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-client-python-sdk#214]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

Looking at [Files.create_data_set](https://zowe-client-python-sdk.readthedocs.io/en/latest/classes/zos_files/files.html#zos_files.zowe.zos_files_for_zowe_sdk.Files.create_data_set) as an example:

![image](https://github.com/zowe/zowe-client-python-sdk/assets/122040687/f7604567-b93e-41ca-b3c0-f30ef7b70ed4)

It takes unnecessary effort to determine what information may be included in the options dictionary. Users may misspell options or include items that are not used. The available parameters for a function should be clear to a user and not hidden within a mutable data structure. 

**Describe your enhancement idea**

Unless specifically dealing with json data that has been parsed into a dictionary, functions should use parameters that explicitly refer to individual pieces of data or classes containing immutable attributes.

**Comment by JTonda** [comment]
Need to determine if we want to use a data class or keyword args & look for all the other methods that might be using generic options (dictionaries).

**Comment by t1m0thyj** [comment]
Do we also want to avoid dictionaries as return types? Currently the `keyring.findCredentials` implementation in the Secrets SDK differs between Node.js which returns an array of `{ account, password }` objects, and Python which returns an array of tuples.

**Comment by zFernand0** [comment]
Resolved in:
- https://github.com/zowe/zowe-client-python-sdk/pull/287
