### ISSUE TITLE
Enhancement request: retrieve contents of a spool file

### ISSUE THREAD

**Issue by sosadchuk** [zowe/zowe-client-python-sdk#23]
Good afternoon,

I would like to request expansion of the existing Jobs class to be able to retrieve spool file contents with specified ddname.

It will require two methods implemented:
- https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_RetrieveSpoolFileContents.htm
- https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_GetListSpoolFiles.htm

I've seen them implemented in PR #18 by @ToineMichielseBroadcom, but I believe we need to split that PR into separate granular changes at least (samples, Files class changes, Jobs class changes).

Please let me know if I can help preparing this one.

Thanks,
Sergei.

**Comment by t1m0thyj** [comment]
`Jobs.get_spool_file_contents` was added to the z/OS Jobs SDK in https://github.com/zowe/zowe-client-python-sdk/pull/21
