### ISSUE TITLE
Enhancement: create sequential or partitioned data set

### ISSUE THREAD

**Issue by sosadchuk** [zowe/zowe-client-python-sdk#25]
Hi,

I would like to request this method implemented in the existing Files class:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_CreateDataSet.htm

**Comment by sosadchuk** [comment]
Created a PR in our fork, please let me know when contribution with enhancements will be permitted

**Comment by t1m0thyj** [comment]
`Files.create_default_dataset` was added to the z/OS Files SDK in https://github.com/zowe/zowe-client-python-sdk/pull/110
