### ISSUE TITLE
[tests]: Organize tests based on the source structure

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-client-python-sdk#265]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

Before the Python SDK reaches the Long Term Support stage, we should reorganize our tests so that they can be easily maintained after the issue below is completed:
- #264 

**Describe your enhancement idea**

Ideally we would run individual tests based on what we are fixin/enhancing.

Here is a before and after based on Pytest's structure of `FILE_PATH::TEST_CLASS::TEST_METHOD`
Before:
- `pytest -s tests/unit/test_zowe_core.py::TestZosmfProfileManager::test_autodiscovery_and_base_profile_loading`

After: (this is just an example of how we could split the tests and the source code too)
- `pytest -s tests/unit/files/create/dataset.py::TestPdsCreation::wrong_alcunit`
- `pytest -s tests/unit/files/create/dataset.py::TestPdsCreation::wrong_recfm`
- `pytest -s tests/unit/jobs/submit/stdin.py::TestJobSubmission::invalid_job_card`
- `pytest -s tests/unit/jobs/download/spool.py::TestJobDownloading::invalid_job_id`

**Describe alternatives you've considered**

N/A

**Provide any additional context**

**Comment by traeok** [comment]
It might also be worth updating the USS tests to cover more functions in the codebase.
