### ISSUE TITLE
Update tests to use context managers

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#288]
Follow up to #145 - now that the SDK APIs are context managers, we should update our tests:
* [ ] All integration tests should use `with` statement when calling SDK APIs
* [ ] [core] Add unit test for SDK API that tests `requests.Session.close` is called after context manager exits

**Comment by aadityasinha-dotcom** [comment]
Hello, please assign this issue to me :relaxed:
