### ISSUE TITLE
feat: Allow logger to be disabled at the class-constructor level

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-client-python-sdk#316]
**Is your feature or enhancement request related to a problem or limitation? Please describe**

- After #310 was implemented...
- It would be great if we allowed the logger to be disabled  as part of the class constructor

**Describe your enhancement idea**

As an example, someone could do `Datasets(profile, log=False)`

**Describe alternatives you've considered**

```python
profile = ProfileManager().load(profile_type="zosmf", validate_schema=False)
ds = Datasets(profile)
Log.close_all()
console = Console(profile)
jobs = Jobs(profile)
```

The above will run off the logger for Datasets abut keep it open for the other classes since they are initialized after the `Log.close_all()` call

**Provide any additional context**

**Comment by aadityasinha-dotcom** [comment]
Would like to work on this issue :relaxed:
