### ISSUE TITLE
Consistent Name for SDK 

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-client-python-sdk#328]
In the README the SDK is referred to as:
* Zowe Client Python SDK
* Zowe Python Client SDK

The name of the SDK should be consistently used and named across SDKs.  Related to https://github.com/zowe/docs-site/issues/3851

**Comment by olamidepeterojo** [comment]
Good day @dkelosky @adam-wolfe, trust you are good? Apart from the inconsistent SDK naming in the README, i also noticed the inconsistency in files like _init_.py, setup.py . Would you like i make changes there or just the README?

**Comment by zFernand0** [comment]
Thanks @olamidepeterojo for the fix
