### ISSUE TITLE
Is the internship only for college student

### ISSUE THREAD

**Issue by richardgreg** [zowe/zowe-client-python-sdk#33]
Hi, the project is a good match for my skill set. One of the initial tasks asks for a "School Enrollment Verification." Does that mean that only college students need to apply?

**Comment by MikeBauerCA** [comment]
Hi @richardgreg 

No, the mentorship program is not strictly for college students. The full eligibility requirements are listed at https://docs.linuxfoundation.org/lfx/mentorship/mentees

I encourage you to apply. You can skip the "School Enrollment Verification" question, or if there is an option to comment then you may enter "self taught".

**Comment by richardgreg** [comment]
Okay, thanks for the response.

**Comment by richardgreg** [comment]
@MikeBauerCA Is one allowed to work on the open issues or they're reserved for the internship?

**Comment by MikeBauerCA** [comment]
Feel free to pick up an issue and run with it - we can adjust the internship content if absolutely needed to focus on other areas of improvement within the project. A good place to start may be with a brief review of the open PR. I think it resolves some open issues.
