### ISSUE TITLE
[zos-files] `download_dsn` should stream contents of data set

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#34]
Currently, the contents of a data set are retrieved as a string with `get_dsn_content` before being written to a file:
https://github.com/zowe/zowe-client-python-sdk/blob/4a413309c144a629bb0e87b7a6fb659a91923e30/src/zos_files/zowe/zos_files_for_zowe_sdk/files.py#L166-L172

To improve performance when downloading large data sets, we should use a stream that buffers reading the REST response and writing to the file. See [here](https://stackoverflow.com/a/57498146/5504760) for an example of using the `requests` library to stream data.

**Comment by t1m0thyj** [comment]
@richardgreg I've tried to assign you to the issue, but outside of the Zowe team it seems that GitHub only allows me to assign to people who have commented on the issue.

**Comment by skorzhevsky** [comment]
Can be closed?
