### ISSUE TITLE
[zos-files] Add method to upload file to USS

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#37]
For this enhancement, we probably want two new methods:
- `upload_file_to_uss` modeled after `upload_file_to_dsn`:
  https://github.com/zowe/zowe-client-python-sdk/blob/4a413309c144a629bb0e87b7a6fb659a91923e30/src/zos_files/zowe/zos_files_for_zowe_sdk/files.py#L194-L201
- `write_to_uss` to call the `requests` library and write data to the USS file using the REST endpoint documented [here](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-write-data-zos-unix-file#PutWriteUnixFile)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue
