### ISSUE TITLE
Add test suites

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#39]
There are some tests in the [develop](https://github.com/zowe/zowe-client-python-sdk/tree/develop/tests) branch that we can model after.

* [x] Unit tests to test individual methods
* [ ] System tests against a z/OSMF instance
* [x] GitHub workflow to automate tests (related to #51)

**Comment by richardgreg** [comment]
I'd like to work on this

**Comment by xtanion** [comment]
Hi, Can I work on this issue?

**Comment by t1m0thyj** [comment]
> Has qithub workflow to automate tests already been implemented in https://github.com/zowe/zowe-client-python-sdk/pull/87 ?

@xtanion Thanks for your interest in this issue! Yes, the workflow to automate tests has been added, so I think this issue can be closed.

There are additional workflows we would like to add in the future, but are not ready to yet (see https://github.com/zowe/zowe-client-python-sdk/issues/51).
