### ISSUE TITLE
[zos-files] Add method to create data set

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#40]
Create a sequential or partitioned data set by POSTing to the endpoint `/zosmf/restfiles/ds/<dsname>` as documented [here](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-create-sequential-partitioned-data-set#CreateDataSet).

This can be implemented by adding new methods to the zos-files SDK: https://github.com/zowe/zowe-client-python-sdk/blob/experimental/src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
* `create_data_set(dataset_name, options)` - where options is a dictionary defining options for the [request body](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-create-sequential-partitioned-data-set#CreateDataSet__Reqbod)
* `create_data_set_like(dataset_name, like_dataset_name)` - shorthand for `create_data_set(dataset_name, {"like": like_dataset_name})`

**Comment by aadityasinha-dotcom** [comment]
Is this issue available? 
Can I work on it?

**Comment by himanshu007-creator** [comment]
> Is this issue available? Can I work on it?

Hey @aadityasinha-dotcom , i am currently working on this issue, got delayed due to examinations. Kindly check back one week later, if there's no progress, feel free to work on this.

**Comment by aadityasinha-dotcom** [comment]
okay, sure
