### ISSUE TITLE
[zos-files] Add method to delete data set

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#41]
Delete a sequential or partitioned data set by sending DELETE to the endpoint `/zosmf/restfiles/ds/<dsname>` as documented [here](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-delete-sequential-partitioned-data-set#DeleteDataSet).

This can be implemented by adding new methods to the zos-files SDK: https://github.com/zowe/zowe-client-python-sdk/blob/experimental/src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
* `delete_data_set(dataset_name, volume)` - where volume is an optional string parameter

Note: The same method can be used to delete members of partitioned data sets by giving it a string `"<dsname>(<member-name>)"`. See https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-delete-partitioned-data-set-member#DeletepartitionedDataSet

**Comment by richardgreg** [comment]
Working on this

**Comment by richardgreg** [comment]
What should the default value of volume be?

**Comment by t1m0thyj** [comment]
> What should the default value of volume be?

The `volume` is optional in most cases (unless the data set is uncataloged). So I believe the volume shouldn't have a default value.

When `volume` is not specified, you would call the REST API `/zosmf/restfiles/ds/<dataset-name>(<member-name>)`.

When `volume` is specified, you would call the REST API `/zosmf/restfiles/ds/-(volume)/<dataset-name>(<member-name>)`.

**Comment by richardgreg** [comment]
Alright. In the API, values in `<>` are variables. Are values in `()` optional values?
