### ISSUE TITLE
[zos-files] Add method to create USS file

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#42]
Create a Unix file or directory by POSTing to the endpoint `/zosmf/restfiles/fs/<filePath>` as documented [here](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-create-unix-file-directory#CreateUnixFile).

This can be implemented by adding new methods to the zos-files SDK: https://github.com/zowe/zowe-client-python-sdk/blob/experimental/src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
* `create_uss_file(file_name, mode)` - where mode is an optional permission string like `rwxr-xr-x`.
* `create_uss_dir(directory_name, mode)` - where mode behaves the same as above.

**Comment by aadityasinha-dotcom** [comment]
Hey!! Can I work on this issue?

**Comment by t1m0thyj** [comment]
@aadityasinha-dotcom Sure, feel free to work on it it 🙂

**Comment by aadityasinha-dotcom** [comment]
Hey, @t1m0thyj I want to ask is this correct?
```python
def create_uss_file(self, file_name, mode):
    """
    Add a file or directory
    Parameters
    ----------
    file_name of the file to add
    mode Ex:- rwxr-xr-x

    """
    custom_args = self.create_custom_request_arguments()
    custom_args["url"] = "{}fs{}".format(self.request_endpoint,file_name)
    response_json = self.request_handler.perform_request("POST", custom_args)
    return response_json
```

**Comment by t1m0thyj** [comment]
@aadityasinha-dotcom Thanks for investigating this, that is a great start 👍 A few comments:

* A JSON payload needs to provided on the request like this: `{ "type": "file", "mode": "rwxr-xr-x" }`. The `type` parameter must always be defined. The `mode` parameter on the function should be optional, and if specified it should be defined on the payload.
* Since `perform_request` expects response code 200 but the API returns 201 on success, you'll need to add `expected_code=[201]` to the `perform_request` call.
* The `file_name` should be supported either with or without a leading slash. You could achieve this with something like:
```custom_args["url"] = "{}fs/{}".format(self.request_endpoint, file_name.lstrip("/"))```
* I'd also suggest renaming `file_name` to `file_path` to be consistent with the z/OSMF API doc.

**Comment by aadityasinha-dotcom** [comment]
@t1m0thyj Regarding JSON payload should I mention it like this :-
```python
data = {
  "type": "file",
  "mode": "rwxr-xr-x"
}
custom_args = self.create_custom_request_arguments()
custom_args["url"] = "{}fs{}".format(self.request_endpoint, filepath_name.lstrip("/"))
response_json = self.request_handler.perform_request("POST", custom_args, data)
return response_json
```

**Comment by t1m0thyj** [comment]
@aadityasinha-dotcom I believe the payload should be defined as `custom_args["params"]`. There is an example here: https://github.com/zowe/zowe-client-python-sdk/blob/master/src/zos_files/zowe/zos_files_for_zowe_sdk/files.py#L50

**Comment by aadityasinha-dotcom** [comment]
Okay, yes

**Comment by aadityasinha-dotcom** [comment]
So, I will put it like `custom_args["params"] = data`?
