### ISSUE TITLE
[zos-files] Add method to delete USS file

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#43]
Delete a Unix file or directory by sending DELETE to the endpoint `/zosmf/restfiles/fs/<filePath>` as documented [here](https://www.ibm.com/docs/en/zos/2.4.0?topic=interface-delete-unix-file-directory#DeleteUnixFile).

This can be implemented by adding new methods to the zos-files SDK: https://github.com/zowe/zowe-client-python-sdk/blob/experimental/src/zos_files/zowe/zos_files_for_zowe_sdk/files.py
* `delete_uss(file_name)` - where expected response code is 204

**Comment by shalearkane** [comment]
Hello, could you assign this issue to me?

**Comment by t1m0thyj** [comment]
@shalearkane Sure, feel free to work on it 🙂

**Comment by shalearkane** [comment]
Hey, I have create a Pull Request for this issue, please could you review it, https://github.com/zowe/zowe-client-python-sdk/pull/48
