### ISSUE TITLE
Accept gzip encoding on zos-files requests

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#45]
This would allow large files to be compressed for faster downloads (and perhaps uploads).

**Comment by shalearkane** [comment]
Hello, I have created a pull request for this issue: https://github.com/zowe/zowe-client-python-sdk/pull/48 please review 😄

**Comment by zFernand0** [comment]
@t1m0thyj can this be closed?

**Comment by t1m0thyj** [comment]
For download operations it has been implemented in the linked PR 👍 

For upload operations it has not been implemented yet, but same is true for the Node.js SDK. I think we can close this issue for now, and wait to see if compression for uploads is requested in the future.
