### ISSUE TITLE
Create GitHub workflows

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#51]
It would be nice for this repo to have fully automated CICD with GitHub Actions 🙂 Ideas for workflows:
* [x] Run unit tests and report coverage
* [x] Perform linting and style checks
* [x] Deploy package updates to PyPI
* [ ] Run system tests in Marist environment

**Comment by aadityasinha-dotcom** [comment]
Can I work on this?

**Comment by zFernand0** [comment]
Closing in favor of:
- #261
