### ISSUE TITLE
[zos-files] Add method to create a zFS file system

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#58]
Add a method to the Python zos-files SDK to call the z/OSMF REST API `POST /zosmf/restfiles/mfs/zfs/<file-system-name>`

* z/OSMF REST API documentation: https://www.ibm.com/docs/en/zos/2.5.0?topic=interface-create-zos-unix-zfs-filesystem
* Python zos-files SDK in the "next" branch: https://github.com/zowe/zowe-client-python-sdk/tree/next/src/zos_files
* Node.js zos-files SDK for comparison: https://github.com/zowe/zowe-cli/blob/master/packages/zosfiles/src/methods/create/Create.ts

**Comment by aadityasinha-dotcom** [comment]
Can I work on this :slightly_smiling_face:

**Comment by t1m0thyj** [comment]
@aadityasinha-dotcom I've responded on Slack. For now the zos-files issues are reserved. I created some new issues (#77 and #78) for other SDKs - feel free to take a look at those :slightly_smiling_face:
