### ISSUE TITLE
[zos-console] Add method to get a command response

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#78]
Add a method to the Python zos-console SDK to call the z/OSMF REST API `GET /zosmf/restconsoles/consoles/<console-name>/solmsgs/C<key-number>`

* z/OSMF REST API documentation: https://www.ibm.com/docs/en/zos/2.5.0?topic=services-get-command-response
* Python zos-console SDK in the "next" branch: https://github.com/zowe/zowe-client-python-sdk/tree/next/src/zos_console
* Node.js zos-console SDK for comparison: https://github.com/zowe/zowe-cli/blob/master/packages/zosconsole/src/CollectCommand.ts

**Comment by aadityasinha-dotcom** [comment]
Assign me this also : smiling_face:
