### ISSUE TITLE
[zos-files] `create_dataset` should fail if required options are missing

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-client-python-sdk#88]
The following options are required:
* Either `like` must be specified, OR
* If `like` is undefined, then `primary` and `lrecl` must be specified

**Comment by t1m0thyj** [comment]
Perhaps we should create convenience functions like the Node.js SDK has for creating specific types of data sets. For example, to create a PDS, the default options are:
`{"alcunit": "CYL", "dsorg": "PO", "primary": 1, "dirblk": 5, "recfm": "FB", "blksize": 6160, "lrecl": 80}`
The current `create_data_set` method works, but it's not easy to remember which of those options I need to specify 😛

**Comment by fbh112** [comment]
I am working  in a client, they are also looking for the function to "create new dataset" in python SDK.   it seems like in nodejs SDK,  the create function is there although.

**Comment by t1m0thyj** [comment]
> I am working in a client usercase, they are also looking for the function to "create new dataset" in python SDK. it seems like in nodejs SDK, the create function is there although.

@fbh112 Thanks for your interest in the Zowe Python SDK 🙂 It has not had a Long Term Support release yet and is still catching up to the Node.js SDK in supported functionality.

We are working to add more functionality to the Python SDK, and a `create_data_set` method has been added in the "next" branch:
https://github.com/zowe/zowe-client-python-sdk/blob/next/src/zos_files/zowe/zos_files_for_zowe_sdk/files.py#L147

The contents of the "next" branch have not been published to PyPI (Python Package Index), so currently it can only be installed from source. It will be a while until we have tested these changes thoroughly enough to be ready to publish them as a stable release.

In the meantime, would it be helpful for your use case if we publish "prerelease" versions of the Zowe Python SDK on PyPI that contain the new experimental functionality such as creating data sets?

**Comment by fbh112** [comment]
@t1m0thyj hi,  thanks for your reply.   Do you know when the "next" branch will be published ?  now they are using cli to create dataset first then using sdk to do the rest. This workaround will be fine for them currently. 

BTW The client is using offline package (e.g whl files) to install the zowe, not via PyPI.

**Comment by t1m0thyj** [comment]
@fbh112 I don't have a specific ETA but hopefully by the end of the month we'll have prerelease packages for the "next" branch published. 🙂

**Comment by t1m0thyj** [comment]
@fbh112 We have prerelease packages (wheels) released on GitHub now: https://github.com/zowe/zowe-client-python-sdk/releases

They are in an alpha/experimental stage so should not be used in a project where stability is important. But if you're interested to try them out and provide feedback feel free.

**Comment by fbh112** [comment]
@t1m0thyj  thanks Tim. I will check if customer want to test this pre-release package.
