### ISSUE TITLE
Python SDK publishing

### ISSUE THREAD

**Issue by MikeBauerCA** [zowe/zowe-client-python-sdk#9]
Similar to zowe/zowe-cli#751. Individual packages published to the Python index. Namespaces/scopes are not currently available. Perhaps we follow this naming scheme:
- `zowe.zos-console-for-zowe-sdk`
- `zowe.zos-files-for-zowe-sdk`
- `zowe.zos-jobs-for-zowe-sdk`
- `zowe.zos-tso-for-zowe-sdk`
- `zowe.zosmf-for-zowe-sdk`

**Comment by MikeBauerCA** [comment]
Note: @gcartier94 I added the zos prefix to the names of some packages for consistency with the Node SDK -> zowe/zowe-cli#750

**Comment by gcartier94** [comment]
@MikeBauerCA pull request #12 created for this.
